### ISSUE TITLE
Frontend Crash (a.realUserName is not a function)

### ISSUE THREAD

**Issue by seppitm** [zxy19/user-decoration#7]
Greetings, i got this error on some Posts if i enable the Plugin:
![grafik](https://github.com/user-attachments/assets/c7aaf504-6c11-4621-a6a7-8f04cb80bb5e)

I have also isntalled the "Nicknames" Extension

**Comment by zxy19** [comment]
Thank you for reporting. However there is no enough information to know what was happing. 

Is the problem occurs just after installing the extension or when doing something else?

Also, could you check the version of user-decoration extension and also the extension installed.

You may use `php flarum info` command.

**Comment by seppitm** [comment]
Sorry, totally forgot about that! I also wanted to say, that your extension is beautiful, i really like how it's Workflow

Flarum core: 1.8.5
PHP version: 8.0.30
MySQL version: 8.0.33
Loaded extensions: Core, date, libxml, openssl, pcre, zlib, bcmath, bz2, calendar, ctype, dba, dom, hash, fileinfo, filter, ftp, gettext, gmp, SPL, iconv, session, json, mbstring, pcntl, standard, posix, readline, Reflection, imap, shmop, SimpleXML, soap, sockets, Phar, exif, sysvmsg, sysvsem, sysvshm, tokenizer, xml, xmlreader, xmlwriter, zip, mysqlnd, imagick, curl, gd, mysqli, PDO, pdo_mysql, xsl, sqlite3, intl, sodium, ldap, tidy, pdo_pgsql, pdo_sqlite, igbinary, redis, Zend OPcache
+--------------------------------------+---------+--------+
| Flarum Extensions                    |         |        |
+--------------------------------------+---------+--------+
| ID                                   | Version | Commit |
+--------------------------------------+---------+--------+
| flarum-flags                         | v1.8.0  |        |
| flarum-tags                          | v1.8.1  |        |
| flarum-approval                      | v1.8.1  |        |
| flarum-markdown                      | v1.8.0  |        |
| flarum-suspend                       | v1.8.1  |        |
| flarum-mentions                      | v1.8.3  |        |
| flarum-subscriptions                 | v1.8.0  |        |
| flarum-bbcode                        | v1.8.0  |        |
| askvortsov-auto-moderator            | v0.1.3  |        |
| v17development-seo                   | v1.8.1  |        |
| askvortsov-rich-text                 | v2.1.7  |        |
| flarum-sticky                        | v1.8.0  |        |
| flarum-lock                          | v1.8.0  |        |
| afrux-forum-widgets-core             | v0.1.7  |        |
| fof-pages                            | 1.0.8   |        |
| fof-byobu                            | 1.3.6   |        |
| ianm-level-ranks                     | 1.1.1   |        |
| fof-user-directory                   | 1.3.3   |        |
| fof-follow-tags                      | 1.2.5   |        |
| fof-formatting                       | 1.0.3   |        |
| flarum-likes                         | v1.8.0  |        |
| wolfgang-demeter-bbcode-5star-rating | v0.1.8  |        |
| webbinaro-age-check                  | 0.0.7   |        |
| v17development-user-badges           | v1.1.0  |        |
| v17development-blog                  | v0.7.7  |        |
| the-turk-stickiest                   | 3.0.1   |        |
| sycho-profile-cover                  | v1.3.5  |        |
| ramesh-dada-mobile-newdiscuss        | 7.2.1   |        |
| ramesh-dada-bbcode-alerts            | 6.21    |        |
| katosdev-signature                   | 1.6     |        |
| justoverclock-hot-discussions        | 0.1.2   |        |
| justoverclock-custom-html-widget     | 0.1.4   |        |
| ianm-syndication                     | 1.3.4   |        |
| foskym-activity-graph                | v0.1.0  |        |
| fof-webhooks                         | 1.2.3   |        |
| fof-user-bio                         | 1.4.0   |        |
| fof-upload                           | 1.5.5   |        |
| fof-terms                            | 1.3.1   |        |
| fof-socialprofile                    | 1.1.6   |        |
| fof-sitemap                          | 2.2.1   |        |
| fof-share-social                     | 1.2.0   |        |
| fof-reactions                        | 1.4.1   |        |
| fof-profile-image-crop               | 1.1.6   |        |
| fof-polls                            | 1.4.2   |        |
| fof-oauth                            | 1.6.10  |        |
| fof-nightmode                        | 1.5.3   |        |
| fof-merge-discussions                | 1.4.1   |        |
| fof-links                            | 1.2.3   |        |
| fof-linguist                         | 1.1.2   |        |
| fof-impersonate                      | 1.1.1   |        |
| fof-ignore-users                     | 1.2.1   |        |
| fof-html-errors                      | 1.1.2   |        |
| fof-drafts                           | 1.2.10  |        |
| fof-doorman                          | 1.1.5   |        |
| fof-cookie-consent                   | 1.1.3   |        |
| fof-best-answer                      | 1.4.5   |        |
| fof-ban-ips                          | 1.1.1   |        |
| fof-anti-spam                        | 1.1.2   |        |
| fof-amazon-affiliation               | 1.1.0   |        |
| flarumite-simple-spoilers            | 1.0.0   |        |
| flarumite-simple-discussion-views    | 1.2.3   |        |
| flarum-statistics                    | v1.8.0  |        |
| flarum-nicknames                     | v1.8.0  |        |
| flarum-lang-german                   | 1.13.0  |        |
| flarum-lang-english                  | v1.8.0  |        |
| flarum-emoji                         | v1.8.0  |        |
| flamarkt-matomo                      | 0.1.0   |        |
| defendervex-bbextend                 | 0.1.1   |        |
| datlechin-link-preview               | v1.4.0  |        |
| datlechin-bbcode-hide-content        | v0.1.6  |        |
| datitisev-post-galleries             | 1.1.1   |        |
| clarkwinkelmann-shadow-ban           | 1.1.0   |        |
| clarkwinkelmann-group-invitation     | 1.0.2   |        |
| clarkwinkelmann-emojionearea         | 1.0.0   |        |
| askvortsov-pwa                       | v3.4.1  |        |
| askvortsov-markdown-tables           | v1.2.1  |        |
| askvortsov-categories                | v3.1.0  |        |
| antoinefr-money                      | v1.3.1  |        |
| afrux-online-users-widget            | v0.1.6  |        |
+--------------------------------------+---------+--------+

**Comment by seppitm** [comment]
Not on all pages, just on some. I just found, that the page has an deleted user account!

**Comment by zxy19** [comment]
Ok, I'v fixed in the latest version v1.1.0. Just update and check if the bug is fixed.😊

**Comment by seppitm** [comment]
It is fixed! Tank you!
